// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package g

import (
	"github.com/dianlight/srat/dbom"
	"github.com/dianlight/srat/dto"
	"gorm.io/cli/gorm/field"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

var ExportedShare = struct {
	Name               field.String
	CreatedAt          field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field[gorm.DeletedAt]
	Disabled           field.Bool
	Users              field.Slice[dbom.SambaUser]
	RoUsers            field.Slice[dbom.SambaUser]
	VetoFiles          field.Struct[datatypes.JSONSlice[string]]
	TimeMachine        field.Bool
	RecycleBin         field.Bool
	GuestOk            field.Bool
	TimeMachineMaxSize field.String
	Usage              field.Struct[dto.HAMountUsage]
	MountPointDataPath field.String
	MountPointDataRoot field.String
	MountPointData     field.Struct[dbom.MountPointPath]
}{
	Name:               field.String{}.WithColumn("name"),
	CreatedAt:          field.Time{}.WithColumn("created_at"),
	UpdatedAt:          field.Time{}.WithColumn("updated_at"),
	DeletedAt:          field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
	Disabled:           field.Bool{}.WithColumn("disabled"),
	Users:              field.Slice[dbom.SambaUser]{}.WithName("Users"),
	RoUsers:            field.Slice[dbom.SambaUser]{}.WithName("RoUsers"),
	VetoFiles:          field.Struct[datatypes.JSONSlice[string]]{}.WithName("VetoFiles"),
	TimeMachine:        field.Bool{}.WithColumn("time_machine"),
	RecycleBin:         field.Bool{}.WithColumn("recycle_bin"),
	GuestOk:            field.Bool{}.WithColumn("guest_ok"),
	TimeMachineMaxSize: field.String{}.WithColumn("time_machine_max_size"),
	Usage:              field.Struct[dto.HAMountUsage]{}.WithName("Usage"),
	MountPointDataPath: field.String{}.WithColumn("mount_point_data_path"),
	MountPointDataRoot: field.String{}.WithColumn("mount_point_data_root"),
	MountPointData:     field.Struct[dbom.MountPointPath]{}.WithName("MountPointData"),
}
