// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package g

import (
	"github.com/dianlight/srat/dto"
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var HDIdleDevice = struct {
	DevicePath     field.String
	IdleTime       field.Number[int]
	CommandType    field.Field[dto.HdidleCommand]
	PowerCondition field.Number[uint8]
	Enabled        field.Field[dto.HdidleEnabled]
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DeletedAt      field.Field[gorm.DeletedAt]
}{
	DevicePath:     field.String{}.WithColumn("device_path"),
	IdleTime:       field.Number[int]{}.WithColumn("idle_time"),
	CommandType:    field.Field[dto.HdidleCommand]{}.WithColumn("command_type"),
	PowerCondition: field.Number[uint8]{}.WithColumn("power_condition"),
	Enabled:        field.Field[dto.HdidleEnabled]{}.WithColumn("enabled"),
	CreatedAt:      field.Time{}.WithColumn("created_at"),
	UpdatedAt:      field.Time{}.WithColumn("updated_at"),
	DeletedAt:      field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
