// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package g

import (
	"gorm.io/cli/gorm/field"
	"gorm.io/gorm"
)

var Property = struct {
	Key       field.String
	Value     field.Field[any]
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field[gorm.DeletedAt]
}{
	Key:       field.String{}.WithColumn("key"),
	Value:     field.Field[any]{}.WithColumn("value"),
	CreatedAt: field.Time{}.WithColumn("created_at"),
	UpdatedAt: field.Time{}.WithColumn("updated_at"),
	DeletedAt: field.Field[gorm.DeletedAt]{}.WithColumn("deleted_at"),
}
