# Markdownlint configuration for SRAT project
# GitHub Flavored Markdown (GFM) compatible configuration
# See https://github.com/DavidAnson/markdownlint for configuration options

# Default state for all rules
default: true

# Disable line length restriction (GFM doesn't enforce this)
MD013: false

# Allow HTML elements for badges and special formatting (GFM allows HTML)
MD033:
  allowed_elements:
    - img
    - a
    - br
    - details
    - summary
    - div
    - span
    - table
    - tr
    - td
    - th
    - thead
    - tbody
    - p
    - kbd

# Don't require H1 to be first heading
MD041: false

# Allow inline HTML (GFM supports HTML)
MD010: false

# Don't enforce blank lines around lists
MD032: false

# Allow bare URLs (GFM supports autolinks)
MD034: false

# Allow emphasis for highlighting
MD036: false

# Allow missing space in headers (for HTML comments)
MD021: false

# Allow trailing punctuation in headers
MD026: false

# Configuration for code blocks (require language specification)
MD040: true

# Configuration for emphasis style (use asterisks for consistency with GFM)
MD049:
  style: asterisk

# Configuration for strong style (use asterisks for consistency with GFM)
MD050:
  style: asterisk

# Allow multiple headers with same content
MD024: false

# Allow first line in file to be anything (for metadata, comments, etc.)
MD041: false

# GitHub Flavored Markdown specific allowances
# MD046: Code block style - allow both indented and fenced
MD046: false

# MD028: Allow blank lines inside blockquotes
MD028: false

# MD022: Headers should be surrounded by blank lines (flexible for GFM)
MD022: false
