# Markdownlint configuration for SRAT project
# See https://github.com/DavidAnson/markdownlint for configuration options

# Disable line length restriction
MD013: false

# Allow HTML elements for badges and special formatting
MD033:
  allowed_elements:
    - img
    - a
    - br
    - details
    - summary
    - div
    - span

# Don't require H1 to be first heading
MD041: false

# Allow inline HTML
MD010: false

# Don't enforce blank lines around lists
MD032: false

# Allow HTML entities and bare URLs for reference links
MD034: false

# Allow emphasis for highlighting
MD036: false

# Allow missing space in headers (for HTML comments)
MD021: false

# Allow trailing punctuation in headers
MD026: false

# Configuration for code blocks
MD040: true  # Require language specification for code blocks

# Configuration for emphasis style
MD049:
  style: asterisk

# Configuration for strong style
MD050:
  style: asterisk

# Allow multiple headers with same content
MD024: false
