FRONTEND_DIRS := ./frontend/
BACKEND_DIRS := ./backend/
VERSION ?= "TEST_INTERNAL_MULTIARCH"



ALL: 
	cd $(BACKEND_DIRS);$(MAKE) AARGS="GOARCH=amd64" SUFFIX="_amd64" VERSION=$(VERSION)
	cd $(BACKEND_DIRS);$(MAKE) AARGS="GOARM=7 GOARCH=arm" SUFFIX="_armv7" VERSION=$(VERSION)
	cd $(BACKEND_DIRS);$(MAKE) AARGS="GOARCH=arm64" SUFFIX="_aarch64" VERSION=$(VERSION)

BUILD:
	cd $(BACKEND_DIRS);$(MAKE) AARGS="$(AARGS)" SUFFIX="$(SUFFIX)" VERSION=$(VERSION)


PREREQUISITE:
	cd $(BACKEND_DIRS);$(MAKE) PREREQUISITE	

.PHONY: clean
clean:
	cd $(FRONTEND_DIRS); bun clean
	cd $(BACKEND_DIRS);$(MAKE) clean

