# Samba username mappings generated by SRAT
# Only usernames requiring Unix normalization are listed.
{{- range .mappings }}
{{ .UnixUsername }} ={{- range .SambaUsernames }} "{{ . }}"{{- end }}
{{- end }}
