// DO NOT EDIT.
// code generated by goenums v0.4.4.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -l clientevent_type.go

package dto

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"math"

	"golang.org/x/exp/constraints"
)

// ClientEventType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type ClientEventType struct {
	clientEventType
}

// clientEventTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the ClientEventType type.
type clientEventTypesContainer struct {
	CLIENTEVENTTYPEHELO            ClientEventType
	CLIENTEVENTTYPEREPAIRLIFECYCLE ClientEventType
}

// ClientEventTypes is a main entry point using the ClientEventType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var ClientEventTypes = clientEventTypesContainer{
	CLIENTEVENTTYPEHELO: ClientEventType{
		clientEventType: clientEventTypeHelo,
	},
	CLIENTEVENTTYPEREPAIRLIFECYCLE: ClientEventType{
		clientEventType: clientEventTypeRepairLifecycle,
	},
}

// invalidClientEventType is an invalid sentinel value for ClientEventType
var invalidClientEventType = ClientEventType{
	clientEventType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (c clientEventTypesContainer) allSlice() []ClientEventType {
	return []ClientEventType{
		ClientEventTypes.CLIENTEVENTTYPEHELO,
		ClientEventTypes.CLIENTEVENTTYPEREPAIRLIFECYCLE,
	}
}

// All returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (c clientEventTypesContainer) All() []ClientEventType {
	return c.allSlice()
}

// ParseClientEventType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseClientEventType(input any) (ClientEventType, error) {
	switch v := input.(type) {
	case ClientEventType:
		return v, nil
	case string:
		if result := stringToClientEventType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToClientEventType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToClientEventType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToClientEventType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidClientEventType, fmt.Errorf("invalid type %T", input)
	}
	return invalidClientEventType, nil
}

// clientEventTypesNameMap is a map of enum values to their ClientEventType representation
// It is used to convert string representations of enum values into their ClientEventType representation.
var clientEventTypesNameMap = map[string]ClientEventType{
	"helo":             ClientEventTypes.CLIENTEVENTTYPEHELO,
	"repair_lifecycle": ClientEventTypes.CLIENTEVENTTYPEREPAIRLIFECYCLE,
}

// stringToClientEventType converts a string representation of an enum value into its ClientEventType representation
// It returns a pointer to the ClientEventType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToClientEventType(s string) *ClientEventType {
	if t, ok := clientEventTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToClientEventType converts a numeric value to a ClientEventType
// It returns a pointer to the ClientEventType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToClientEventType[T constraints.Integer | constraints.Float](num T) *ClientEventType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(ClientEventTypes.allSlice()) {
		return nil
	}
	result := ClientEventTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveClientEventTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveClientEventTypes(f func(ClientEventType)) {
	for _, p := range ClientEventTypes.allSlice() {
		f(p)
	}
}

// validClientEventTypes is a map of enum values to their validity
var validClientEventTypes = map[ClientEventType]bool{
	ClientEventTypes.CLIENTEVENTTYPEHELO:            true,
	ClientEventTypes.CLIENTEVENTTYPEREPAIRLIFECYCLE: true,
}

// IsValid checks whether the ClientEventTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (c ClientEventType) IsValid() bool {
	return validClientEventTypes[c]
}

// MarshalJSON implements the json.Marshaler interface for ClientEventType.
// It returns the JSON representation of the enum value as a byte slice.
func (c ClientEventType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for ClientEventType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (c *ClientEventType) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newc, err := ParseClientEventType(by)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for ClientEventType.
// It returns the string representation of the enum value as a byte slice
func (c ClientEventType) MarshalText() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for ClientEventType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (c *ClientEventType) UnmarshalText(by []byte) error {
	newc, err := ParseClientEventType(by)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// Scan implements the database/sql.Scanner interface for ClientEventType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (c *ClientEventType) Scan(value any) error {
	newc, err := ParseClientEventType(value)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// Value implements the database/sql/driver.Valuer interface for ClientEventType.
// It returns the string representation of the enum value.
func (c ClientEventType) Value() (driver.Value, error) {
	return c.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for ClientEventType.
// It returns the binary representation of the enum value as a byte slice.
func (c ClientEventType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + c.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for ClientEventType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (c *ClientEventType) UnmarshalBinary(by []byte) error {
	newc, err := ParseClientEventType(by)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for ClientEventType.
// It returns the string representation of the enum value.
func (c ClientEventType) MarshalYAML() ([]byte, error) {
	return []byte(c.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (c *ClientEventType) UnmarshalYAML(by []byte) error {
	newc, err := ParseClientEventType(by)
	if err != nil {
		return err
	}
	*c = newc
	return nil
}

// clienteventtypeNames is a constant string slice containing all enum values cononical absolute names
const clienteventtypeNames = "helorepair_lifecycle"

// clienteventtypeNamesMap is a map of enum values to their canonical absolute
// name positions within the clienteventtypeNames string slice
var clienteventtypeNamesMap = map[ClientEventType]string{
	ClientEventTypes.CLIENTEVENTTYPEHELO:            clienteventtypeNames[0:4],
	ClientEventTypes.CLIENTEVENTTYPEREPAIRLIFECYCLE: clienteventtypeNames[4:20],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (c ClientEventType) String() string {
	if str, ok := clienteventtypeNamesMap[c]; ok {
		return str
	}
	return fmt.Sprintf("clienteventtype(%d)", c.clientEventType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [2]struct{}
	_ = x[clientEventTypeHelo]
	_ = x[clientEventTypeRepairLifecycle-1]
}
