// DO NOT EDIT.
// code generated by goenums v0.4.4.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums hdidle_enabled.go

package dto

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// HdidleEnabled is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type HdidleEnabled struct {
	hdidleEnabled
}

// hdidleEnabledsContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the HdidleEnabled type.
type hdidleEnabledsContainer struct {
	YESENABLED    HdidleEnabled
	CUSTOMENABLED HdidleEnabled
	NOENABLED     HdidleEnabled
}

// HdidleEnableds is a main entry point using the HdidleEnabled type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var HdidleEnableds = hdidleEnabledsContainer{
	YESENABLED: HdidleEnabled{
		hdidleEnabled: yesEnabled,
	},
	CUSTOMENABLED: HdidleEnabled{
		hdidleEnabled: customEnabled,
	},
	NOENABLED: HdidleEnabled{
		hdidleEnabled: noEnabled,
	},
}

// invalidHdidleEnabled is an invalid sentinel value for HdidleEnabled
var invalidHdidleEnabled = HdidleEnabled{
	hdidleEnabled: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (h hdidleEnabledsContainer) allSlice() []HdidleEnabled {
	return []HdidleEnabled{
		HdidleEnableds.YESENABLED,
		HdidleEnableds.CUSTOMENABLED,
		HdidleEnableds.NOENABLED,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (h hdidleEnabledsContainer) All() iter.Seq[HdidleEnabled] {
	return func(yield func(HdidleEnabled) bool) {
		for _, v := range h.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

// ParseHdidleEnabled parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseHdidleEnabled(input any) (HdidleEnabled, error) {
	switch v := input.(type) {
	case HdidleEnabled:
		return v, nil
	case string:
		if result := stringToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToHdidleEnabled(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToHdidleEnabled(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToHdidleEnabled(v); result != nil {
			return *result, nil
		}
	default:
		return invalidHdidleEnabled, fmt.Errorf("invalid type %T", input)
	}
	return invalidHdidleEnabled, nil
}

// hdidleEnabledsNameMap is a map of enum values to their HdidleEnabled representation
// It is used to convert string representations of enum values into their HdidleEnabled representation.
var hdidleEnabledsNameMap = map[string]HdidleEnabled{
	"yes":    HdidleEnableds.YESENABLED,
	"custom": HdidleEnableds.CUSTOMENABLED,
	"no":     HdidleEnableds.NOENABLED,
}

// stringToHdidleEnabled converts a string representation of an enum value into its HdidleEnabled representation
// It returns a pointer to the HdidleEnabled representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToHdidleEnabled(s string) *HdidleEnabled {
	if t, ok := hdidleEnabledsNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToHdidleEnabled converts a numeric value to a HdidleEnabled
// It returns a pointer to the HdidleEnabled representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToHdidleEnabled[T constraints.Integer | constraints.Float](num T) *HdidleEnabled {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(HdidleEnableds.allSlice()) {
		return nil
	}
	result := HdidleEnableds.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveHdidleEnableds iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveHdidleEnableds(f func(HdidleEnabled)) {
	for _, p := range HdidleEnableds.allSlice() {
		f(p)
	}
}

// validHdidleEnableds is a map of enum values to their validity
var validHdidleEnableds = map[HdidleEnabled]bool{
	HdidleEnableds.YESENABLED:    true,
	HdidleEnableds.CUSTOMENABLED: true,
	HdidleEnableds.NOENABLED:     true,
}

// IsValid checks whether the HdidleEnableds value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (h HdidleEnabled) IsValid() bool {
	return validHdidleEnableds[h]
}

// MarshalJSON implements the json.Marshaler interface for HdidleEnabled.
// It returns the JSON representation of the enum value as a byte slice.
func (h HdidleEnabled) MarshalJSON() ([]byte, error) {
	return []byte("\"" + h.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for HdidleEnabled.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (h *HdidleEnabled) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newh, err := ParseHdidleEnabled(by)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for HdidleEnabled.
// It returns the string representation of the enum value as a byte slice
func (h HdidleEnabled) MarshalText() ([]byte, error) {
	return []byte("\"" + h.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for HdidleEnabled.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (h *HdidleEnabled) UnmarshalText(by []byte) error {
	newh, err := ParseHdidleEnabled(by)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// Scan implements the database/sql.Scanner interface for HdidleEnabled.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (h *HdidleEnabled) Scan(value any) error {
	newh, err := ParseHdidleEnabled(value)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// Value implements the database/sql/driver.Valuer interface for HdidleEnabled.
// It returns the string representation of the enum value.
func (h HdidleEnabled) Value() (driver.Value, error) {
	return h.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for HdidleEnabled.
// It returns the binary representation of the enum value as a byte slice.
func (h HdidleEnabled) MarshalBinary() ([]byte, error) {
	return []byte("\"" + h.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for HdidleEnabled.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (h *HdidleEnabled) UnmarshalBinary(by []byte) error {
	newh, err := ParseHdidleEnabled(by)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for HdidleEnabled.
// It returns the string representation of the enum value.
func (h HdidleEnabled) MarshalYAML() ([]byte, error) {
	return []byte(h.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (h *HdidleEnabled) UnmarshalYAML(by []byte) error {
	newh, err := ParseHdidleEnabled(by)
	if err != nil {
		return err
	}
	*h = newh
	return nil
}

// hdidleenabledNames is a constant string slice containing all enum values cononical absolute names
const hdidleenabledNames = "yescustomno"

// hdidleenabledNamesMap is a map of enum values to their canonical absolute
// name positions within the hdidleenabledNames string slice
var hdidleenabledNamesMap = map[HdidleEnabled]string{
	HdidleEnableds.YESENABLED:    hdidleenabledNames[0:3],
	HdidleEnableds.CUSTOMENABLED: hdidleenabledNames[3:9],
	HdidleEnableds.NOENABLED:     hdidleenabledNames[9:11],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (h HdidleEnabled) String() string {
	if str, ok := hdidleenabledNamesMap[h]; ok {
		return str
	}
	return fmt.Sprintf("hdidleenabled(%d)", h.hdidleEnabled)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[yesEnabled]
	_ = x[customEnabled-1]
	_ = x[noEnabled-2]
}
