// code generated by goenums v0.4.0 at Jun 27 14:48:10. DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums goenums update_process_state.goupdate_process_state.go

package dto

import (
	"bytes"
	"context"
	"database/sql/driver"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// UpdateProcessState is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type UpdateProcessState struct {
	updateProcessState
	Name string
}

// updateProcessStatesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the UpdateProcessState type.
type updateProcessStatesContainer struct {
	UPDATESTATUSIDLE             UpdateProcessState
	UPDATESTATUSCHECKING         UpdateProcessState
	UPDATESTATUSNOUPGRDE         UpdateProcessState
	UPDATESTATUSUPGRADEAVAILABLE UpdateProcessState
	UPDATESTATUSDOWNLOADING      UpdateProcessState
	UPDATESTATUSDOWNLOADCOMPLETE UpdateProcessState
	UPDATESTATUSEXTRACTING       UpdateProcessState
	UPDATESTATUSEXTRACTCOMPLETE  UpdateProcessState
	UPDATESTATUSINSTALLING       UpdateProcessState
	UPDATESTATUSINSTALLCOMPLETE  UpdateProcessState
	UPDATESTATUSERROR            UpdateProcessState
}

// UpdateProcessStates is a main entry point using the UpdateProcessState type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var UpdateProcessStates = updateProcessStatesContainer{
	UPDATESTATUSIDLE: UpdateProcessState{
		updateProcessState: UpdateStatusIdle,
		Name:               "Idle",
	},
	UPDATESTATUSCHECKING: UpdateProcessState{
		updateProcessState: UpdateStatusChecking,
		Name:               "Checking",
	},
	UPDATESTATUSNOUPGRDE: UpdateProcessState{
		updateProcessState: UpdateStatusNoUpgrde,
		Name:               "NoUpgrade",
	},
	UPDATESTATUSUPGRADEAVAILABLE: UpdateProcessState{
		updateProcessState: UpdateStatusUpgradeAvailable,
		Name:               "Available",
	},
	UPDATESTATUSDOWNLOADING: UpdateProcessState{
		updateProcessState: UpdateStatusDownloading,
		Name:               "Downloading",
	},
	UPDATESTATUSDOWNLOADCOMPLETE: UpdateProcessState{
		updateProcessState: UpdateStatusDownloadComplete,
		Name:               "Downloaded",
	},
	UPDATESTATUSEXTRACTING: UpdateProcessState{
		updateProcessState: UpdateStatusExtracting,
		Name:               "Extractiong",
	},
	UPDATESTATUSEXTRACTCOMPLETE: UpdateProcessState{
		updateProcessState: UpdateStatusExtractComplete,
		Name:               "Extracted",
	},
	UPDATESTATUSINSTALLING: UpdateProcessState{
		updateProcessState: UpdateStatusInstalling,
		Name:               "Installing",
	},
	UPDATESTATUSINSTALLCOMPLETE: UpdateProcessState{
		updateProcessState: UpdateStatusInstallComplete,
		Name:               "(Ready for restart)",
	},
	UPDATESTATUSERROR: UpdateProcessState{
		updateProcessState: UpdateStatusError,
		Name:               "Error",
	},
}

// invalidUpdateProcessState is an invalid sentinel value for UpdateProcessState
var invalidUpdateProcessState = UpdateProcessState{}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (u updateProcessStatesContainer) allSlice() []UpdateProcessState {
	return []UpdateProcessState{
		UpdateProcessStates.UPDATESTATUSIDLE,
		UpdateProcessStates.UPDATESTATUSCHECKING,
		UpdateProcessStates.UPDATESTATUSNOUPGRDE,
		UpdateProcessStates.UPDATESTATUSUPGRADEAVAILABLE,
		UpdateProcessStates.UPDATESTATUSDOWNLOADING,
		UpdateProcessStates.UPDATESTATUSDOWNLOADCOMPLETE,
		UpdateProcessStates.UPDATESTATUSEXTRACTING,
		UpdateProcessStates.UPDATESTATUSEXTRACTCOMPLETE,
		UpdateProcessStates.UPDATESTATUSINSTALLING,
		UpdateProcessStates.UPDATESTATUSINSTALLCOMPLETE,
		UpdateProcessStates.UPDATESTATUSERROR,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (u updateProcessStatesContainer) All() iter.Seq[UpdateProcessState] {
	return func(yield func(UpdateProcessState) bool) {
		for _, v := range u.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

// ParseUpdateProcessState parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseUpdateProcessState(input any) (UpdateProcessState, error) {
	var res = invalidUpdateProcessState
	switch v := input.(type) {
	case UpdateProcessState:
		return v, nil
	case string:
		res = stringToUpdateProcessState(v)
	case fmt.Stringer:
		res = stringToUpdateProcessState(v.String())
	case []byte:
		res = stringToUpdateProcessState(string(v))
	case int:
		res = numberToUpdateProcessState(v)
	case int8:
		res = numberToUpdateProcessState(v)
	case int16:
		res = numberToUpdateProcessState(v)
	case int32:
		res = numberToUpdateProcessState(v)
	case int64:
		res = numberToUpdateProcessState(v)
	case uint:
		res = numberToUpdateProcessState(v)
	case uint8:
		res = numberToUpdateProcessState(v)
	case uint16:
		res = numberToUpdateProcessState(v)
	case uint32:
		res = numberToUpdateProcessState(v)
	case uint64:
		res = numberToUpdateProcessState(v)
	case float32:
		res = numberToUpdateProcessState(v)
	case float64:
		res = numberToUpdateProcessState(v)
	default:
		return res, fmt.Errorf("invalid type %T", input)
	}
	return res, nil
}

// updateProcessStatesNameMap is a map of enum values to their UpdateProcessState representation
// It is used to convert string representations of enum values into their UpdateProcessState representation.
var updateProcessStatesNameMap = map[string]UpdateProcessState{
	"NeedRestart": UpdateProcessStates.UPDATESTATUSINSTALLCOMPLETE,
}

// stringToUpdateProcessState converts a string representation of an enum value into its UpdateProcessState representation
// It returns the UpdateProcessState representation of the enum value if the string is valid
// Otherwise, it returns invalidUpdateProcessState
func stringToUpdateProcessState(s string) UpdateProcessState {
	if t, ok := updateProcessStatesNameMap[s]; ok {
		return t
	}
	return invalidUpdateProcessState
}

// numberToUpdateProcessState converts a numeric value to a UpdateProcessState
// It returns the UpdateProcessState representation of the enum value if the numeric value is valid
// Otherwise, it returns invalidUpdateProcessState
func numberToUpdateProcessState[T constraints.Integer | constraints.Float](num T) UpdateProcessState {
	f := float64(num)
	if math.Floor(f) != f {
		return invalidUpdateProcessState
	}
	i := int(f)
	if i <= 0 || i > len(UpdateProcessStates.allSlice()) {
		return invalidUpdateProcessState
	}
	return UpdateProcessStates.allSlice()[i]
}

// ExhaustiveUpdateProcessStates iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveUpdateProcessStates(f func(UpdateProcessState)) {
	for _, p := range UpdateProcessStates.allSlice() {
		f(p)
	}
}

// validUpdateProcessStates is a map of enum values to their validity
var validUpdateProcessStates = map[UpdateProcessState]bool{
	UpdateProcessStates.UPDATESTATUSIDLE:             true,
	UpdateProcessStates.UPDATESTATUSCHECKING:         true,
	UpdateProcessStates.UPDATESTATUSNOUPGRDE:         true,
	UpdateProcessStates.UPDATESTATUSUPGRADEAVAILABLE: true,
	UpdateProcessStates.UPDATESTATUSDOWNLOADING:      true,
	UpdateProcessStates.UPDATESTATUSDOWNLOADCOMPLETE: true,
	UpdateProcessStates.UPDATESTATUSEXTRACTING:       true,
	UpdateProcessStates.UPDATESTATUSEXTRACTCOMPLETE:  true,
	UpdateProcessStates.UPDATESTATUSINSTALLING:       true,
	UpdateProcessStates.UPDATESTATUSINSTALLCOMPLETE:  true,
	UpdateProcessStates.UPDATESTATUSERROR:            true,
}

// IsValid checks whether the UpdateProcessStates value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (u UpdateProcessState) IsValid() bool {
	return validUpdateProcessStates[u]
}

// MarshalJSON implements the json.Marshaler interface for UpdateProcessState.
// It returns the JSON representation of the enum value as a byte slice.
func (u UpdateProcessState) MarshalJSON() ([]byte, error) {
	return []byte("\"" + u.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for UpdateProcessState.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (u *UpdateProcessState) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newu, err := ParseUpdateProcessState(b)
	if err != nil {
		return err
	}
	*u = newu
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for UpdateProcessState.
// It returns the string representation of the enum value as a byte slice
func (u UpdateProcessState) MarshalText() ([]byte, error) {
	return []byte("\"" + u.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for UpdateProcessState.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (u *UpdateProcessState) UnmarshalText(b []byte) error {
	newu, err := ParseUpdateProcessState(b)
	if err != nil {
		return err
	}
	*u = newu
	return nil
}

// Scan implements the database/sql.Scanner interface for UpdateProcessState.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (u *UpdateProcessState) Scan(value any) error {
	newu, err := ParseUpdateProcessState(value)
	if err != nil {
		return err
	}
	*u = newu
	return nil
}

// Value implements the database/sql/driver.Valuer interface for UpdateProcessState.
// It returns the string representation of the enum value.
func (u UpdateProcessState) Value() (driver.Value, error) {
	return u.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for UpdateProcessState.
// It returns the binary representation of the enum value as a byte slice.
func (u UpdateProcessState) MarshalBinary() ([]byte, error) {
	return []byte("\"" + u.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for UpdateProcessState.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (u *UpdateProcessState) UnmarshalBinary(b []byte) error {
	newu, err := ParseUpdateProcessState(b)
	if err != nil {
		return err
	}
	*u = newu
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for UpdateProcessState.
// It returns the string representation of the enum value.
// It returns an error if the enum value is invalid.
func (u UpdateProcessState) MarshalYAML() (any, error) {
	return u.String(), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for UpdateProcessState.
// It parses the string representation of the enum value from the YAML node.
// It returns an error if the YAML node does not contain a valid enum value.
func (u *UpdateProcessState) UnmarshalYAML(ctx context.Context, f func(any) error) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}
	return f(u.String())
}

// updateprocessstateNames is a constant string slice containing all enum values cononical absolute names
const updateprocessstateNames = "UpdateStatusIdleUpdateStatusCheckingUpdateStatusNoUpgrdeUpdateStatusUpgradeAvailableUpdateStatusDownloadingUpdateStatusDownloadCompleteUpdateStatusExtractingUpdateStatusExtractCompleteUpdateStatusInstallingNeedRestartUpdateStatusError"

// updateprocessstateNamesMap is a map of enum values to their canonical absolute
// name positions within the updateprocessstateNames string slice
var updateprocessstateNamesMap = map[UpdateProcessState]string{
	UpdateProcessStates.UPDATESTATUSIDLE:             updateprocessstateNames[0:16],
	UpdateProcessStates.UPDATESTATUSCHECKING:         updateprocessstateNames[16:36],
	UpdateProcessStates.UPDATESTATUSNOUPGRDE:         updateprocessstateNames[36:56],
	UpdateProcessStates.UPDATESTATUSUPGRADEAVAILABLE: updateprocessstateNames[56:84],
	UpdateProcessStates.UPDATESTATUSDOWNLOADING:      updateprocessstateNames[84:107],
	UpdateProcessStates.UPDATESTATUSDOWNLOADCOMPLETE: updateprocessstateNames[107:135],
	UpdateProcessStates.UPDATESTATUSEXTRACTING:       updateprocessstateNames[135:157],
	UpdateProcessStates.UPDATESTATUSEXTRACTCOMPLETE:  updateprocessstateNames[157:184],
	UpdateProcessStates.UPDATESTATUSINSTALLING:       updateprocessstateNames[184:206],
	UpdateProcessStates.UPDATESTATUSINSTALLCOMPLETE:  updateprocessstateNames[206:217],
	UpdateProcessStates.UPDATESTATUSERROR:            updateprocessstateNames[217:234],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (u UpdateProcessState) String() string {
	if str, ok := updateprocessstateNamesMap[u]; ok {
		return str
	}
	return fmt.Sprintf("updateprocessstate(%d)", u.updateProcessState)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [11]struct{}
	_ = x[UpdateStatusIdle-0]
	_ = x[UpdateStatusChecking-1]
	_ = x[UpdateStatusNoUpgrde-2]
	_ = x[UpdateStatusUpgradeAvailable-3]
	_ = x[UpdateStatusDownloading-4]
	_ = x[UpdateStatusDownloadComplete-5]
	_ = x[UpdateStatusExtracting-6]
	_ = x[UpdateStatusExtractComplete-7]
	_ = x[UpdateStatusInstalling-8]
	_ = x[UpdateStatusInstallComplete-9]
	_ = x[UpdateStatusError-10]
}
