---
name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 <title>"
labels: ["bug"]
body:
  - type: dropdown
    id: problem_type
    attributes:
      label: "Problem Type"
      description: What is the problem type?
      multiple: true
      options:
        - Frontend UI
        - Addon Crash
        - Addon Update
        - Addon Startup
        - Addon Functionality
        - HA Integration
        - Installation
        - Performance
        - Security
        - Integration
        - Documentation
        - Samba
        - Other
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: "Version"
      description: What is the current version of the addon ?
      placeholder: "e.g. 2026.02.1"
    validations:
      required: true
  - type: input
    id: arch
    attributes:
      label: "Architecture"
      description: What architecture are you on ?
      placeholder: "aarch64 amd64 ..."
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      placeholder: "HasOS VM ..."
    validations:
      required: true      
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the bug you are experiencing."
      placeholder: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Steps to Reproduce"
      description: "Describe the steps to reproduce the behavior:"
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
    validations:
      required: true 
  - type: textarea
    id: srat_config
    attributes:
      label: "SRAT Config"
      description: Please paste the full (remove only password and ssh keys) SRAT config. This will be automatically formatted into code, so no need for backticks.
      render: json
    validations:
      required: false      
  - type: textarea
    id: addon_config
    attributes:
      label: "Addon Config"
      description: Please paste the full (remove only password and ssh keys) addon config. This will be automatically formatted into code, so no need for backticks.
      render: json
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Addon Logs"
      description: Please paste the full log that appears when starting the addon (including banner). This will be automatically formatted into code, so no need for backticks.
      render: text
    validations:
      required: false
  - type: textarea
    id: console
    attributes:
      label: "Console Logs"
      description: Please paste relevant log from your browser console if are availables
      render: text
    validations:
      required: false
