// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	config "github.com/dianlight/srat/config"
	patherr "github.com/dianlight/srat/converter/patherr"
	dbom "github.com/dianlight/srat/dbom"
	dto "github.com/dianlight/srat/dto"
	osutil "github.com/snapcore/snapd/osutil"
)

type ConfigToDbomConverterImpl struct{}

func (c *ConfigToDbomConverterImpl) ConfigToSambaUser(source config.Config, target *dbom.SambaUser) error {
	if source.Username != "" {
		target.Username = source.Username
	}
	if source.Password != "" {
		target.Password = source.Password
	}
	return nil
}
func (c *ConfigToDbomConverterImpl) ExportedShareToShare(source dbom.ExportedShare, target *config.Share) error {
	if source.Name != "" {
		target.Name = source.Name
	}
	if source.MountPointData.Path != "" {
		target.Path = source.MountPointData.Path
	}
	if source.MountPointData.FSType != "" {
		target.FS = source.MountPointData.FSType
	}
	if source.Disabled != false {
		target.Disabled = source.Disabled
	}
	if source.Users != nil {
		target.Users = make([]string, len(source.Users))
		for i := 0; i < len(source.Users); i++ {
			target.Users[i] = SambaUserToString(source.Users[i])
		}
	}
	if source.RoUsers != nil {
		target.RoUsers = make([]string, len(source.RoUsers))
		for j := 0; j < len(source.RoUsers); j++ {
			target.RoUsers[j] = SambaUserToString(source.RoUsers[j])
		}
	}
	if source.TimeMachine != false {
		target.TimeMachine = source.TimeMachine
	}
	if source.Usage != "" {
		target.Usage = string(source.Usage)
	}
	return nil
}
func (c *ConfigToDbomConverterImpl) SambaUserToUser(source dbom.SambaUser, target *config.User) error {
	if source.Username != "" {
		target.Username = source.Username
	}
	if source.Password != "" {
		target.Password = source.Password
	}
	return nil
}
func (c *ConfigToDbomConverterImpl) ShareToExportedShareNoMountPointPath(source config.Share, target *dbom.ExportedShare, context *dbom.SambaUsers) error {
	if source.Name != "" {
		target.Name = source.Name
	}
	if source.Disabled != false {
		target.Disabled = source.Disabled
	}
	if source.Users != nil {
		target.Users = make([]dbom.SambaUser, len(source.Users))
		for i := 0; i < len(source.Users); i++ {
			dbomSambaUser, err := StringToSambaUser(source.Users[i], context)
			if err != nil {
				return patherr.Wrap(err, patherr.Field("Users"), patherr.Index(i))
			}
			target.Users[i] = dbomSambaUser
		}
	}
	if source.RoUsers != nil {
		target.RoUsers = make([]dbom.SambaUser, len(source.RoUsers))
		for j := 0; j < len(source.RoUsers); j++ {
			dbomSambaUser2, err := StringToSambaUser(source.RoUsers[j], context)
			if err != nil {
				return patherr.Wrap(err, patherr.Field("RoUsers"), patherr.Index(j))
			}
			target.RoUsers[j] = dbomSambaUser2
		}
	}
	if source.TimeMachine != false {
		target.TimeMachine = source.TimeMachine
	}
	if source.Usage != "" {
		target.Usage = dto.HAMountUsage(source.Usage)
	}
	if source.Path != "" {
		target.MountPointDataPath = source.Path
	}
	return nil
}
func (c *ConfigToDbomConverterImpl) ShareToMountPointPath(source config.Share, target *dbom.MountPointPath) error {
	if source.Path != "" {
		target.Path = source.Path
	}
	if source.Path != "" {
		target.Type = pathToType(source.Path)
	}
	if source.Path != "" {
		target.Device = PathToSource(source.Path)
	}
	if source.FS != "" {
		target.FSType = source.FS
	}
	if source.Path != "" {
		xbool, err := osutil.IsMounted(source.Path)
		if err != nil {
			return patherr.Wrap(err, patherr.Field("IsMounted"))
		}
		target.IsMounted = xbool
	}
	return nil
}
func (c *ConfigToDbomConverterImpl) UserToUSambaUser(source config.User, target *dbom.SambaUser) error {
	if source.Username != "" {
		target.Username = source.Username
	}
	if source.Password != "" {
		target.Password = source.Password
	}
	return nil
}
