// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	dto "github.com/dianlight/srat/dto"
	github "github.com/google/go-github/v69/github"
)

type GitHubToDtoImpl struct{}

func (c *GitHubToDtoImpl) ReleaseAssetToBinaryAsset(source *github.ReleaseAsset, target *dto.BinaryAsset) error {
	if source != nil {
		if source.Size != nil {
			target.Size = *source.Size
		}
		if source.ID != nil {
			target.ID = *source.ID
		}
	}
	return nil
}
func (c *GitHubToDtoImpl) RepositoryReleaseToReleaseAsset(source *github.RepositoryRelease, target *dto.ReleaseAsset) error {
	if source != nil {
		_ = source
	}
	return nil
}
