// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	dto "github.com/dianlight/srat/dto"
	mount "github.com/dianlight/srat/homeassistant/mount"
)

type HaSupervisorToDtoImpl struct{}

func (c *HaSupervisorToDtoImpl) SharedResourceToMount(source dto.SharedResource, target *mount.Mount) error {
	if source.Name != "" {
		pString := source.Name
		target.Name = &pString
	}
	if source.Name != "" {
		pString2 := source.Name
		target.Share = &pString2
	}
	if source.Usage != "" {
		target.Usage = hAMountUsageToMountUsage(source.Usage)
	}
	return nil
}
