// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	dto "github.com/dianlight/srat/dto"
	lsblk "github.com/dianlight/srat/lsblk"
	xhashes "github.com/shomali11/util/xhashes"
)

type LsblkToDtoConverterImpl struct{}

func (c *LsblkToDtoConverterImpl) LsblkInfoToMountPointData(source *lsblk.LSBKInfo, target *dto.MountPointData) error {
	if source != nil {
		if source.Mountpoint != "" {
			target.Path = source.Mountpoint
		}
		if source.Mountpoint != "" {
			target.PathHash = xhashes.MD5(source.Mountpoint)
		}
		if source.Mountpoint != "" {
			target.Type = pathToType(source.Mountpoint)
		}
		if source.Fstype != "" {
			pString := source.Fstype
			target.FSType = &pString
		}
		if source.Name != "" {
			target.Device = source.Name
		}
		if source.Mountpoint != "" {
			target.IsMounted = isMounted(source.Mountpoint)
		}
	}
	return nil
}
