// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	dbom "github.com/dianlight/srat/dbom"
	mount "github.com/u-root/u-root/pkg/mount"
)

type MountToDbomImpl struct{}

func (c *MountToDbomImpl) MountToMountPointPath(source *mount.MountPoint, target *dbom.MountPointPath) error {
	if source != nil {
		if source.Path != "" {
			target.Path = source.Path
		}
		if source.Path != "" {
			target.Root = source.Path
		}
		if source.Device != "" {
			target.Type = pathToType(source.Device)
		}
		if source.Device != "" {
			xstring, err := deviceToDeviceId(source.Device)
			if err != nil {
				return err
			}
			target.DeviceId = xstring
		}
		if source.FSType != "" {
			target.FSType = source.FSType
		}
		if source.Data != "" {
			pDbomMounDataFlags, err := stringToMounFlags(source.Data)
			if err != nil {
				return err
			}
			target.Data = pDbomMounDataFlags
		}
	}
	return nil
}
