// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	dto "github.com/dianlight/srat/dto"
	process "github.com/shirou/gopsutil/v4/process"
)

type ProcessToDtoImpl struct{}

func (c *ProcessToDtoImpl) ProcessToProcessStatus(source *process.Process) (*dto.ProcessStatus, error) {
	var pDtoProcessStatus *dto.ProcessStatus
	if source != nil {
		var dtoProcessStatus dto.ProcessStatus
		dtoProcessStatus.Pid = (*source).Pid
		xstring, err := (*source).Name()
		if err != nil {
			return nil, err
		}
		dtoProcessStatus.Name = xstring
		xint64, err := (*source).CreateTime()
		if err != nil {
			return nil, err
		}
		timeTime, err := int64ToTime(xint64)
		if err != nil {
			return nil, err
		}
		dtoProcessStatus.CreateTime = timeTime
		xfloat64, err := (*source).CPUPercent()
		if err != nil {
			return nil, err
		}
		dtoProcessStatus.CPUPercent = xfloat64
		xfloat32, err := (*source).MemoryPercent()
		if err != nil {
			return nil, err
		}
		dtoProcessStatus.MemoryPercent = xfloat32
		processOpenFilesStatList, err := (*source).OpenFiles()
		if err != nil {
			return nil, err
		}
		xint, err := sliceToLen(processOpenFilesStatList)
		if err != nil {
			return nil, err
		}
		dtoProcessStatus.OpenFiles = xint
		netConnectionStatList, err := (*source).Connections()
		if err != nil {
			return nil, err
		}
		xint2, err := sliceToLen(netConnectionStatList)
		if err != nil {
			return nil, err
		}
		dtoProcessStatus.Connections = xint2
		stringList, err := (*source).Status()
		if err != nil {
			return nil, err
		}
		if stringList != nil {
			dtoProcessStatus.Status = make([]string, len(stringList))
			for i := 0; i < len(stringList); i++ {
				dtoProcessStatus.Status[i] = stringList[i]
			}
		}
		xbool, err := (*source).IsRunning()
		if err != nil {
			return nil, err
		}
		dtoProcessStatus.IsRunning = xbool
		pProcessProcessList, err := (*source).Children()
		if err != nil {
			return nil, err
		}
		if pProcessProcessList != nil {
			dtoProcessStatus.Children = make([]*dto.ProcessStatus, len(pProcessProcessList))
			for j := 0; j < len(pProcessProcessList); j++ {
				pDtoProcessStatus2, err := c.ProcessToProcessStatus(pProcessProcessList[j])
				if err != nil {
					return nil, err
				}
				dtoProcessStatus.Children[j] = pDtoProcessStatus2
			}
		}
		pDtoProcessStatus = &dtoProcessStatus
	}
	return pDtoProcessStatus, nil
}
