// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"fmt"
	"testing"

	"github.com/dianlight/srat/dbom"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&dbom.HDIdleDevice{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&dbom.HDIdleDevice{}) fail: %s", err)
	}
}

func Test_hDIdleDeviceQuery(t *testing.T) {
	hDIdleDevice := newHDIdleDevice(_gen_test_db)
	hDIdleDevice = *hDIdleDevice.As(hDIdleDevice.TableName())
	_do := hDIdleDevice.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(hDIdleDevice.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <hd_idle_devices> fail:", err)
		return
	}

	_, ok := hDIdleDevice.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from hDIdleDevice success")
	}

	err = _do.Create(&dbom.HDIdleDevice{})
	if err != nil {
		t.Error("create item in table <hd_idle_devices> fail:", err)
	}

	err = _do.Save(&dbom.HDIdleDevice{})
	if err != nil {
		t.Error("create item in table <hd_idle_devices> fail:", err)
	}

	err = _do.CreateInBatches([]*dbom.HDIdleDevice{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Select(hDIdleDevice.ALL).Take()
	if err != nil {
		t.Error("Take() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <hd_idle_devices> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*dbom.HDIdleDevice{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Select(hDIdleDevice.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Select(hDIdleDevice.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <hd_idle_devices> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.ScanByPage(&dbom.HDIdleDevice{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <hd_idle_devices> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <hd_idle_devices> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <hd_idle_devices> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <hd_idle_devices> fail:", err)
	}
}
