// Code generated by MockGen. DO NOT EDIT.
// Source: ../service (interfaces: VolumeServiceInterface)
//
// Generated by this command:
//
//	mockgen -write_generate_directive -destination mock_volume_service_test.go -package api_test ../service VolumeServiceInterface
//

// Package api_test is a generated GoMock package.
package api_test

import (
	reflect "reflect"

	dto "github.com/dianlight/srat/dto"
	errors "gitlab.com/tozd/go/errors"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -destination mock_volume_service_test.go -package api_test ../service VolumeServiceInterface

// MockVolumeServiceInterface is a mock of VolumeServiceInterface interface.
type MockVolumeServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockVolumeServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockVolumeServiceInterfaceMockRecorder is the mock recorder for MockVolumeServiceInterface.
type MockVolumeServiceInterfaceMockRecorder struct {
	mock *MockVolumeServiceInterface
}

// NewMockVolumeServiceInterface creates a new mock instance.
func NewMockVolumeServiceInterface(ctrl *gomock.Controller) *MockVolumeServiceInterface {
	mock := &MockVolumeServiceInterface{ctrl: ctrl}
	mock.recorder = &MockVolumeServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumeServiceInterface) EXPECT() *MockVolumeServiceInterfaceMockRecorder {
	return m.recorder
}

// GetVolumesData mocks base method.
func (m *MockVolumeServiceInterface) GetVolumesData() (*dto.BlockInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolumesData")
	ret0, _ := ret[0].(*dto.BlockInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolumesData indicates an expected call of GetVolumesData.
func (mr *MockVolumeServiceInterfaceMockRecorder) GetVolumesData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolumesData", reflect.TypeOf((*MockVolumeServiceInterface)(nil).GetVolumesData))
}

// MountVolume mocks base method.
func (m *MockVolumeServiceInterface) MountVolume(md dto.MountPointData) errors.E {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MountVolume", md)
	ret0, _ := ret[0].(errors.E)
	return ret0
}

// MountVolume indicates an expected call of MountVolume.
func (mr *MockVolumeServiceInterfaceMockRecorder) MountVolume(md any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MountVolume", reflect.TypeOf((*MockVolumeServiceInterface)(nil).MountVolume), md)
}

// NotifyClient mocks base method.
func (m *MockVolumeServiceInterface) NotifyClient() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyClient")
}

// NotifyClient indicates an expected call of NotifyClient.
func (mr *MockVolumeServiceInterfaceMockRecorder) NotifyClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyClient", reflect.TypeOf((*MockVolumeServiceInterface)(nil).NotifyClient))
}

// UnmountVolume mocks base method.
func (m *MockVolumeServiceInterface) UnmountVolume(id uint, force, lazy bool) errors.E {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmountVolume", id, force, lazy)
	ret0, _ := ret[0].(errors.E)
	return ret0
}

// UnmountVolume indicates an expected call of UnmountVolume.
func (mr *MockVolumeServiceInterfaceMockRecorder) UnmountVolume(id, force, lazy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmountVolume", reflect.TypeOf((*MockVolumeServiceInterface)(nil).UnmountVolume), id, force, lazy)
}
