// Code generated by MockGen. DO NOT EDIT.
// Source: ../service (interfaces: BroadcasterServiceInterface)
//
// Generated by this command:
//
//	mockgen -write_generate_directive -destination mock_broadcaster_service_test.go -package api_test ../service BroadcasterServiceInterface
//

// Package api_test is a generated GoMock package.
package api_test

import (
	reflect "reflect"

	sse "github.com/danielgtaylor/huma/v2/sse"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -destination mock_broadcaster_service_test.go -package api_test ../service BroadcasterServiceInterface

// MockBroadcasterServiceInterface is a mock of BroadcasterServiceInterface interface.
type MockBroadcasterServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcasterServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockBroadcasterServiceInterfaceMockRecorder is the mock recorder for MockBroadcasterServiceInterface.
type MockBroadcasterServiceInterfaceMockRecorder struct {
	mock *MockBroadcasterServiceInterface
}

// NewMockBroadcasterServiceInterface creates a new mock instance.
func NewMockBroadcasterServiceInterface(ctrl *gomock.Controller) *MockBroadcasterServiceInterface {
	mock := &MockBroadcasterServiceInterface{ctrl: ctrl}
	mock.recorder = &MockBroadcasterServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcasterServiceInterface) EXPECT() *MockBroadcasterServiceInterfaceMockRecorder {
	return m.recorder
}

// BroadcastMessage mocks base method.
func (m *MockBroadcasterServiceInterface) BroadcastMessage(msg any) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastMessage", msg)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BroadcastMessage indicates an expected call of BroadcastMessage.
func (mr *MockBroadcasterServiceInterfaceMockRecorder) BroadcastMessage(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastMessage", reflect.TypeOf((*MockBroadcasterServiceInterface)(nil).BroadcastMessage), msg)
}

// ProcessHttpChannel mocks base method.
func (m *MockBroadcasterServiceInterface) ProcessHttpChannel(send sse.Sender) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessHttpChannel", send)
}

// ProcessHttpChannel indicates an expected call of ProcessHttpChannel.
func (mr *MockBroadcasterServiceInterfaceMockRecorder) ProcessHttpChannel(send any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessHttpChannel", reflect.TypeOf((*MockBroadcasterServiceInterface)(nil).ProcessHttpChannel), send)
}
