// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/cli/gorm/typed"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func HDIdleDeviceQuery[T any](db *gorm.DB, opts ...clause.Expression) _HDIdleDeviceQueryInterface[T] {
	return _HDIdleDeviceQueryImpl[T]{
		Interface: typed.G[T](db, opts...),
	}
}

type _HDIdleDeviceQueryInterface[T any] interface {
	typed.Interface[T]
	All(ctx context.Context) ([]*T, error)
}

type _HDIdleDeviceQueryImpl[T any] struct {
	typed.Interface[T]
}

func (e _HDIdleDeviceQueryImpl[T]) All(ctx context.Context) ([]*T, error) {
	var sb strings.Builder
	_params := make([]any, 0, 1)

	sb.WriteString("SELECT * FROM ?")
	_params = append(_params, clause.Table{Name: clause.CurrentTable})

	var result []*T
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}
