// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"github.com/dianlight/srat/dbom"
	"gorm.io/cli/gorm/typed"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func MountPointPathQuery[T any](db *gorm.DB, opts ...clause.Expression) _MountPointPathQueryInterface[T] {
	return _MountPointPathQueryImpl[T]{
		Interface: typed.G[T](db, opts...),
	}
}

type _MountPointPathQueryInterface[T any] interface {
	typed.Interface[T]
	FindByPath(ctx context.Context, path string) (*dbom.MountPointPath, error)
	FindByDevice(ctx context.Context, device string) ([]*dbom.MountPointPath, error)
}

type _MountPointPathQueryImpl[T any] struct {
	typed.Interface[T]
}

func (e _MountPointPathQueryImpl[T]) FindByPath(ctx context.Context, path string) (*dbom.MountPointPath, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM ? WHERE path=?")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, path)

	var result *dbom.MountPointPath
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _MountPointPathQueryImpl[T]) FindByDevice(ctx context.Context, device string) ([]*dbom.MountPointPath, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("SELECT * FROM ? WHERE device_id=?")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, device)

	var result []*dbom.MountPointPath
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}
