// Code generated by 'gorm.io/cli/gorm'. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/cli/gorm/typed"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

func SambaUserQuery[T any](db *gorm.DB, opts ...clause.Expression) _SambaUserQueryInterface[T] {
	return _SambaUserQueryImpl[T]{
		Interface: typed.G[T](db, opts...),
	}
}

type _SambaUserQueryInterface[T any] interface {
	typed.Interface[T]
	GetAdmin(ctx context.Context) (T, error)
	DeleteByName(ctx context.Context, username string) (int, error)
	RenameUser(ctx context.Context, oldname string, newname string) (*T, error)
}

type _SambaUserQueryImpl[T any] struct {
	typed.Interface[T]
}

func (e _SambaUserQueryImpl[T]) GetAdmin(ctx context.Context) (T, error) {
	var sb strings.Builder
	_params := make([]any, 0, 1)

	sb.WriteString("SELECT * FROM ? WHERE is_admin = true AND deleted_at IS NULL LIMIT 1")
	_params = append(_params, clause.Table{Name: clause.CurrentTable})

	var result T
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _SambaUserQueryImpl[T]) DeleteByName(ctx context.Context, username string) (int, error) {
	var sb strings.Builder
	_params := make([]any, 0, 2)

	sb.WriteString("UPDATE ? SET deleted_at=DATETIME('now') WHERE username = ? AND is_admin = false AND deleted_at IS NULL RETURNING 1")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, username)

	var result int
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}

func (e _SambaUserQueryImpl[T]) RenameUser(ctx context.Context, oldname string, newname string) (*T, error) {
	var sb strings.Builder
	_params := make([]any, 0, 3)

	sb.WriteString("UPDATE ? SET username = ? WHERE username = ? AND is_admin = true RETURNING *")
	_params = append(_params, clause.Table{Name: clause.CurrentTable}, newname, oldname)

	var result *T
	err := e.Raw(sb.String(), _params...).Scan(ctx, &result)
	return result, err
}
