package oauthkeys

import (
	"crypto/ed25519"
	"encoding/base64"
	"testing"

	"github.com/stretchr/testify/require"
)

type interopVector struct {
	SeedB64url   string `json:"seed_b64url"`
	PubB64url    string `json:"pub_b64url"`
	ClientID     string `json:"client_id"`
	StringToSign string `json:"string_to_sign"`
	SigB64url    string `json:"sig_b64url"`
}

func TestInteropVector_GoVerifiesTS(t *testing.T) {
	// Hardcoded vector generated by Go (seed = "0123456789abcdef0123456789abcdef")
	// Also stored at oauth_broker/tests/testdata/interop-vector.json for TS
	v := interopVector{
		SeedB64url:   "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY",
		PubB64url:    "I7xUkSwebpLEqGglyGfif_3FVb_71CRPF6Jqv__ull0",
		ClientID:     "-3lwIZ4m0fQeZtOhVlEIWiB1kQPSFSiEgAQISDZU_e4",
		StringToSign: "-3lwIZ4m0fQeZtOhVlEIWiB1kQPSFSiEgAQISDZU_e4\nPOST\n/v1/start\n1700000000\ntest-nonce-1234567890123456\n47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU",
		SigB64url:    "5KrU1gZse5Xsaal7AEDKfXTFIT5OZ4PHZ4G7k1OAnjj7yuZBkQt89UasjijfcWlk5YBXWzTINakGEWwbnXsSCw",
	}

	// Verify client_id
	cid, err := ComputeClientID(v.PubB64url)
	require.NoError(t, err)
	require.Equal(t, v.ClientID, cid)

	// Verify Go-generated sig with Go verifier
	pubRaw, err := base64.RawURLEncoding.DecodeString(v.PubB64url)
	require.NoError(t, err)
	sigRaw, err := base64.RawURLEncoding.DecodeString(v.SigB64url)
	require.NoError(t, err)
	require.True(t, ed25519.Verify(ed25519.PublicKey(pubRaw), []byte(v.StringToSign), sigRaw))

	// Sign same StringToSign with Go using fixed seed and compare to vector sig (deterministic)
	seedRaw, err := base64.RawURLEncoding.DecodeString(v.SeedB64url)
	require.NoError(t, err)
	priv := ed25519.NewKeyFromSeed(seedRaw)
	sig2 := ed25519.Sign(priv, []byte(v.StringToSign))
	sig2B64 := base64.RawURLEncoding.EncodeToString(sig2)
	require.Equal(t, v.SigB64url, sig2B64)

	// Tamper should fail
	require.False(t, ed25519.Verify(ed25519.PublicKey(pubRaw), []byte(v.StringToSign+"x"), sigRaw))
}
