/**
 * Cross-language interop test: fixed Ed25519 keypair + known-answer vectors shared
 * with the Go implementation (backend/src/internal/oauthkeys/keys_test.go).
 *
 * The seed is SHA256("srat-interop-test-seed") — deterministic, so both the TS and
 * Go implementations derive the same key and (because Ed25519 is deterministic)
 * produce the exact same signature for the same StringToSign. This test pins the
 * TS side; the Go side asserts the same vectors. If either side changes the
 * StringToSign canonicalization, base64url encoding, or key derivation, one of
 * these assertions fails.
 */
import { describe, it, expect, vi, afterEach } from "vitest";
import { createTestApp, registerClient, registerInstance, signedStartRequest, signedSessionRequest } from "./utils.js";
import { bodyHashBase64Url, buildStringToSign, computeClientId, signStringToSign, verifyEd25519 } from "../src/crypto.js";
import vector from "./testdata/interop-vector.json";

// Fixed known-answer vectors (generated by Go, verified identical in TS).
const SEED_B64 = "WFke_MEL51VDHYP4vsoahH-OVFitV_1F2R5gMXUAm2U"; // 32B raw seed == JWK d
const PUB_B64 = "eY33ep1dYLmq54IAFGk8jTiCT0Exsi0EzUyNPot4ddU"; // 32B raw pub == JWK x
const CLIENT_ID = "l7wo8EkfW8XQhpuez21Gt3aVd0Esp9f_tgN0OH7JEXA";
const BODY = '{"instance_id":"ha-interop","redirect_url":"https://srat.example/cb"}';
const BODY_HASH_B64 = "3-LZCHH-aCv07EN2EhpnZgbsNAAVBPz6R3KTFxU0FEI";
const T = "1767225600";
const NONCE = "interop-nonce-20260101";
const EXPECTED_SIG = "NS-toNCT7P3y3n_Fs9XlK3R8iJUeBo38vq6ZBhd5x4TzU5KP6S3RRUlShTCg6cQX7rt8BCD4NQP6eAJzQq9TAg";

const STS = buildStringToSign(CLIENT_ID, "POST", "/v1/instances/register", T, NONCE, BODY_HASH_B64);

describe("cross-language interop (fixed Go↔TS vectors)", () => {
  it("TS reproduces Go vector from testdata/interop-vector.json (bodyHash, client_id, sig)", async () => {
    const v = vector as {
      seed_b64url: string;
      pub_b64url: string;
      client_id: string;
      string_to_sign: string;
      sig_b64url: string;
    };
    // bodyHash component of the vector StringToSign (hash of empty body for GET-free POST vector)
    expect(v.string_to_sign.split("\n").at(-1)).toBe("47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU");
    expect(bodyHashBase64Url("")).toBe("47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU");
    expect(computeClientId(v.pub_b64url)).toBe(v.client_id);
    // deterministic signature must equal the Go-generated one
    expect(await signStringToSign(v.seed_b64url, v.pub_b64url, v.string_to_sign)).toBe(v.sig_b64url);
    // and it verifies
    expect(await verifyEd25519(v.pub_b64url, v.string_to_sign, v.sig_b64url)).toBe(true);
    expect(await verifyEd25519(v.pub_b64url, v.string_to_sign + "x", v.sig_b64url)).toBe(false);
  });

  it("bodyHash matches Go BodyHash (b64url SHA256 of raw bytes)", () => {
    expect(bodyHashBase64Url(BODY)).toBe(BODY_HASH_B64);
    // empty body for GET matches Go BodyHash("")
    expect(bodyHashBase64Url("")).toBe("47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU");
  });

  it("computeClientId matches Go ComputeClientID", () => {
    expect(computeClientId(PUB_B64)).toBe(CLIENT_ID);
  });

  it("signStringToSign reproduces the Go-generated signature (deterministic Ed25519)", async () => {
    const sig = await signStringToSign(SEED_B64, PUB_B64, STS);
    expect(sig).toBe(EXPECTED_SIG);
  });

  it("verifyEd25519 accepts the Go-produced signature and rejects tampering", async () => {
    expect(await verifyEd25519(PUB_B64, STS, EXPECTED_SIG)).toBe(true);
    // tampered message
    expect(await verifyEd25519(PUB_B64, STS + "x", EXPECTED_SIG)).toBe(false);
    // tampered signature
    expect(await verifyEd25519(PUB_B64, STS, "A".repeat(86))).toBe(false);
  });

  it("full broker flow accepts the fixed Go-compatible keypair", async () => {
    const kp = { publicKeyB64Url: PUB_B64, privateKeyB64Url: SEED_B64, clientId: CLIENT_ID };
    const mockFetch = vi.fn(async () =>
      new Response(JSON.stringify({ access_token: "at", token_type: "bearer", expires_in: 3600, account_id: "acc1" }), { status: 200 })
    ) as unknown as typeof fetch;
    const { app } = createTestApp(undefined, { fetchImpl: mockFetch });

    // Self-certifying client registration with the fixed key
    const reg = await registerClient(app, kp);
    expect(reg.status).toBe(201);

    // Instance register signed with the fixed key
    const inst = await registerInstance(app, "ha-interop", "https://srat.example/cb", kp);
    expect(inst.status).toBe(200);

    // Start signed with the fixed key
    const start = await signedStartRequest(app, { provider: "dropbox", srat_callback_url: "https://srat.example/cb", instance_id: "ha-interop" }, kp);
    expect(start.status).toBe(200);
    const { session_id } = (await start.json()) as { session_id: string };

    // Complete the flow so session is fetchable, then GET /v1/session signed
    await app.request(`/v1/callback?code=c&state=${session_id}`, { headers: { accept: "application/json" } });
    const got = await signedSessionRequest(app, session_id, kp);
    expect(got.status).toBe(200);
    const body = (await got.json()) as { token_json: string };
    expect(JSON.parse(body.token_json).access_token).toBe("at");
  });
});

afterEach(() => {
  vi.useRealTimers();
});
