openapi: 3.1.0
info:
  title: API Supervisor Home Assistant - Hardware
  version: 2025.3.0
  description: API per interagire con l'hardware tramite il Supervisor di Home Assistant.
  contact:
    email: lucio.tarantino@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about HA API
  url: https://developers.home-assistant.io/docs/api/supervisor/endpoints/#hardware
servers:
  - url: http://supervisor/core # Sostituisci con l'URL corretto
paths:
  /hardware:
    get:
      summary: Ottieni informazioni sull'hardware.
      operationId: getHardware
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Informazioni sull'hardware.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hardware'
components:
  schemas:
    Hardware:
      type: object
      properties:
        name:
          type: string
          description: Nome del dispositivo hardware.
        path:
          type: string
          description: Percorso del dispositivo hardware.
        subsystem:
          type: string
          description: Sottosistema del dispositivo hardware.
        device_type:
          type: string
          description: Tipo del dispositivo hardware.
        capabilities:
          type: array
          items:
            type: string
          description: Capacità del dispositivo hardware.
        used_by:
          type: array
          items:
            type: string
          description: Componenti che utilizzano il dispositivo hardware.
        attributes:
          type: object
          description: Attributi del dispositivo hardware.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
