openapi: 3.0.0
info:
  title: API Supervisor Home Assistant - Ingress
  version: 2025.3.0
  description: API per interagire con l'Ingress tramite il Supervisor di Home Assistant.
  contact:
    email: lucio.tarantino@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about HA API
  url: https://developers.home-assistant.io/docs/api/supervisor/endpoints/#ingress
servers:
  - url: http://supervisor/core # Sostituisci con l'URL corretto
paths:
  /ingress/panels:
    get:
      summary: Ottieni la lista dei pannelli Ingress.
      operationId: getIngressPanels
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Lista dei pannelli Ingress.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum: ["ok"]
                  data:
                    type: object
                    properties:
                      panels:
                        type: object
                        additionalProperties:
                          $ref: "#/components/schemas/IngressPanel"
  /ingress/session:
    post:
      summary: Crea una nuova sessione Ingress.
      operationId: createIngressSession
      security:
        - bearerAuth: []
      requestBody:
        description: Dati per la creazione della sessione Ingress.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IngressSessionCreate"
      responses:
        "200":
          description: Sessione Ingress creata con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    enum: ["ok"]
                  data:
                    $ref: "#/components/schemas/IngressSession"
        "400":
          description: Richiesta non valida.
  /ingress/validate_session:
    post:
      summary: Validate an ingress session, extending it's validity period.
      operationId: validateIngressSession
      security:
        - bearerAuth: []
      requestBody:
        description: The token for the ingress session
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IngressSession"
      responses:
        "200":
          description: Sessione Ingress creata con successo.
        "400":
          description: Richiesta non valida.
components:
  schemas:
    IngressPanel:
      type: object
      properties:
        enable:
          type: boolean
          description: Indica se il pannello è abilitato.
        title:
          type: string
          description: Titolo del pannello.
        icon:
          type: string
          description: Icona del pannello.
        admin:
          type: boolean
          description: Indica se il pannello è per amministratore.
    IngressSessionCreate:
      type: object
      properties:
        user_id:
          type: string
          description: The ID of the user authenticated for the new session 
    IngressSession:
      type: object
      properties:
        session:
          type: string
          description: ID della sessione.
          example: "b7c23590-3620-4f20-9017-814d10703523"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
