// Package discovery provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package discovery

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateDiscoveryRequest defines model for CreateDiscoveryRequest.
type CreateDiscoveryRequest struct {
	// Config Configuration object with service-specific details.
	Config map[string]interface{} `json:"config"`

	// Service Name of the service to register. Must match an entry in the add-on's
	// config.yaml 'discovery' array.
	Service string `json:"service"`
}

// DiscoveryService A discovery service registered by an add-on.
type DiscoveryService struct {
	// Addon Slug of the add-on that registered this service.
	Addon *string `json:"addon,omitempty"`

	// Config Configuration data for the service (free-form JSON).
	Config *map[string]interface{} `json:"config,omitempty"`

	// Service Name of the service being discovered.
	Service *string `json:"service,omitempty"`

	// Uuid Unique identifier for this discovery message.
	Uuid *openapi_types.UUID `json:"uuid,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Human-readable error message.
	Message *string `json:"message,omitempty"`
	Result  *string `json:"result,omitempty"`
}

// SimpleOkResponse defines model for SimpleOkResponse.
type SimpleOkResponse struct {
	Result *string `json:"result,omitempty"`
}

// CreateDiscoveryServiceJSONRequestBody defines body for CreateDiscoveryService for application/json ContentType.
type CreateDiscoveryServiceJSONRequestBody = CreateDiscoveryRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListDiscoveryServices request
	ListDiscoveryServices(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDiscoveryServiceWithBody request with any body
	CreateDiscoveryServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDiscoveryService(ctx context.Context, body CreateDiscoveryServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDiscoveryService request
	DeleteDiscoveryService(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDiscoveryService request
	GetDiscoveryService(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListDiscoveryServices(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDiscoveryServicesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDiscoveryServiceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDiscoveryServiceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDiscoveryService(ctx context.Context, body CreateDiscoveryServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDiscoveryServiceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteDiscoveryService(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDiscoveryServiceRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDiscoveryService(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDiscoveryServiceRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDiscoveryServicesRequest generates requests for ListDiscoveryServices
func NewListDiscoveryServicesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/discovery")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDiscoveryServiceRequest calls the generic CreateDiscoveryService builder with application/json body
func NewCreateDiscoveryServiceRequest(server string, body CreateDiscoveryServiceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDiscoveryServiceRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateDiscoveryServiceRequestWithBody generates requests for CreateDiscoveryService with any type of body
func NewCreateDiscoveryServiceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/discovery")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDiscoveryServiceRequest generates requests for DeleteDiscoveryService
func NewDeleteDiscoveryServiceRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/discovery/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDiscoveryServiceRequest generates requests for GetDiscoveryService
func NewGetDiscoveryServiceRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/discovery/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListDiscoveryServicesWithResponse request
	ListDiscoveryServicesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDiscoveryServicesResponse, error)

	// CreateDiscoveryServiceWithBodyWithResponse request with any body
	CreateDiscoveryServiceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDiscoveryServiceResponse, error)

	CreateDiscoveryServiceWithResponse(ctx context.Context, body CreateDiscoveryServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDiscoveryServiceResponse, error)

	// DeleteDiscoveryServiceWithResponse request
	DeleteDiscoveryServiceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteDiscoveryServiceResponse, error)

	// GetDiscoveryServiceWithResponse request
	GetDiscoveryServiceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDiscoveryServiceResponse, error)
}

type ListDiscoveryServicesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			Discovery *[]DiscoveryService `json:"discovery,omitempty"`
		} `json:"data,omitempty"`
		Result *string `json:"result,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ListDiscoveryServicesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDiscoveryServicesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateDiscoveryServiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			// Uuid UUID of the created discovery service.
			Uuid *openapi_types.UUID `json:"uuid,omitempty"`
		} `json:"data,omitempty"`
		Result *string `json:"result,omitempty"`
	}
	JSON400 *ErrorResponse
	JSON403 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateDiscoveryServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDiscoveryServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteDiscoveryServiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SimpleOkResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteDiscoveryServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDiscoveryServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDiscoveryServiceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Data A discovery service registered by an add-on.
		Data   *DiscoveryService `json:"data,omitempty"`
		Result *string           `json:"result,omitempty"`
	}
	JSON404 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetDiscoveryServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDiscoveryServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListDiscoveryServicesWithResponse request returning *ListDiscoveryServicesResponse
func (c *ClientWithResponses) ListDiscoveryServicesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDiscoveryServicesResponse, error) {
	rsp, err := c.ListDiscoveryServices(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDiscoveryServicesResponse(rsp)
}

// CreateDiscoveryServiceWithBodyWithResponse request with arbitrary body returning *CreateDiscoveryServiceResponse
func (c *ClientWithResponses) CreateDiscoveryServiceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDiscoveryServiceResponse, error) {
	rsp, err := c.CreateDiscoveryServiceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDiscoveryServiceResponse(rsp)
}

func (c *ClientWithResponses) CreateDiscoveryServiceWithResponse(ctx context.Context, body CreateDiscoveryServiceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDiscoveryServiceResponse, error) {
	rsp, err := c.CreateDiscoveryService(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDiscoveryServiceResponse(rsp)
}

// DeleteDiscoveryServiceWithResponse request returning *DeleteDiscoveryServiceResponse
func (c *ClientWithResponses) DeleteDiscoveryServiceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteDiscoveryServiceResponse, error) {
	rsp, err := c.DeleteDiscoveryService(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDiscoveryServiceResponse(rsp)
}

// GetDiscoveryServiceWithResponse request returning *GetDiscoveryServiceResponse
func (c *ClientWithResponses) GetDiscoveryServiceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetDiscoveryServiceResponse, error) {
	rsp, err := c.GetDiscoveryService(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDiscoveryServiceResponse(rsp)
}

// ParseListDiscoveryServicesResponse parses an HTTP response from a ListDiscoveryServicesWithResponse call
func ParseListDiscoveryServicesResponse(rsp *http.Response) (*ListDiscoveryServicesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDiscoveryServicesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				Discovery *[]DiscoveryService `json:"discovery,omitempty"`
			} `json:"data,omitempty"`
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateDiscoveryServiceResponse parses an HTTP response from a CreateDiscoveryServiceWithResponse call
func ParseCreateDiscoveryServiceResponse(rsp *http.Response) (*CreateDiscoveryServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDiscoveryServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				// Uuid UUID of the created discovery service.
				Uuid *openapi_types.UUID `json:"uuid,omitempty"`
			} `json:"data,omitempty"`
			Result *string `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteDiscoveryServiceResponse parses an HTTP response from a DeleteDiscoveryServiceWithResponse call
func ParseDeleteDiscoveryServiceResponse(rsp *http.Response) (*DeleteDiscoveryServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDiscoveryServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SimpleOkResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetDiscoveryServiceResponse parses an HTTP response from a GetDiscoveryServiceWithResponse call
func ParseGetDiscoveryServiceResponse(rsp *http.Response) (*GetDiscoveryServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDiscoveryServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Data A discovery service registered by an add-on.
			Data   *DiscoveryService `json:"data,omitempty"`
			Result *string           `json:"result,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
