name: golangci-lint

on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  workflow_dispatch:

env:
  GOLANG_LINT_VERSION: "v1.51.2"

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest
          args: -D errcheck
          working-directory: ./backend/src/
