name: golang-tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  GOLANG_VERSION: "1.23.4"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - shell: bash
        run: |
          GOBIN=/usr/local/bin/ go install github.com/swaggo/swag/cmd/swag@latest
          cd backend
          make test
