name: golang-tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  GOLANG_VERSION: "1.23.4"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      - shell: bash
        run: |
          lsblk -e7 -b -J -o name,path,fsavail,fssize,fstype,pttype,fsused,fsuse%,mountpoint,label,uuid,rm,hotplug,serial,state,group,type,alignment,wwn,hctl,tran,subsystems,rev,vendor,model
          cd backend
          make test
